apiVersion: v1
kind: Service
metadata:
  name: gollab-postgres-service
  namespace: gollab-demo-namespace
spec:
  type: ClusterIP
  selector:
    app: gollab-postgres
  ports:
    - port: 5432
      targetPort: 5432
