apiVersion: v1
kind: Service
metadata:
  name: gollab-backend
  namespace: gollab-demo-namespace
spec:
  type: NodePort
  selector:
    app: gollab-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
