name: Pull Request CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-unit-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build application
        run: ./scripts/ci/build-go.sh
      - name: Run Unit Tests
        run: ./scripts/ci/run-unit-tests.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: [build-and-unit-test]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run Linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          DISABLE_GIT: true

  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build-and-unit-test]
    permissions:
      packages: write
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Set lower-case repository owner
        run: echo "OWNER_LC=${REPO_OWNER,,}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/gollab-backend:ci-${{ github.sha }}
